### ISSUE TITLE
Refactoring broke adding new items to scatter list

### ISSUE THREAD

**Issue by wojtekpil** [Zylann/godot_scatter_plugin#14]
After latest commit  I cannot add new items to scatter list. It seems that methods ```add_pattern(...)``` and ```remove_pattern(...)``` were renamed with underscore prefix. And calls to ```ur.add_do_method(self, "add_pattern", path);``` doesn't work anymore.

**Comment by nosdregamon** [comment]
Having the same problem, here.

**Comment by Zylann** [comment]
Fixed by  #15
